# experiment1.yaml

# General settings
debug: false
compile: false
load_from_checkpoint: false
exp_name: "causalmnist_exp2_betamax005"

system:
  device: "cuda"          # or "cpu", "mps", etc.
  accelerator: "cuda"
  seed: 1234
  world_size: 1           # this can be adjusted based on available GPUs

data:
  root_dir: "/local/eb/adam2392/"
  model_dir: "/local/eb/adam2392/CausalMNIST/vae_reduction/"
  batch_size: 128
  num_workers: 4
  img_size: 32
  graph_type: "chain"
  val_split: 0.2

optimizer:
  lr: 0.0003
  betas: [0.9, 0.95]
  weight_decay: 0.0001

training:
  max_epochs: 2000
  grad_accum_steps: 16
  check_samples_every_n_epoch: 5
  cycle_length: 10

model:
  latent_dim: 32
  num_blocks_per_stage: 3

scheduler:
  type: "cosine"
  lr_min: 6e-5

beta:
  beta_min: 0.00025
  beta_max: 0.005
