# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/ciflows",
        "doc_host": "https://adam2392.github.io",
        "git_url": "https://github.com/adam2392/ciflows",
        "lib_path": "ciflows",
    },
    "syms": {
        "ciflows.core": {"ciflows.core.foo": ("core.html#foo", "ciflows/core.py")},
        "ciflows.data": {},
        "ciflows.lightning": {},
        "ciflows.loss": {},
        "ciflows.model": {},
    },
}
